package org.example.model;

import jakarta.persistence.*;//jpa provides the ORM
/**
 * Represents a Product entity mapped to the "products" database table.
 *
 * This class uses JPA annotations to define the ORM mapping between the class and the database.
 * Each instance corresponds to a row in the "products" table.
 */
@Entity//table starts
@Table(name="products")
public class Product {
    /** The primary key for the product, auto-generated by the database. */
    @Id
    @GeneratedValue(strategy= GenerationType.IDENTITY)//auto-increment the primary key
    @Column
    private int id;
    /** The name of the product. */
    @Column
    private String name;
    /** The price of the product. */
    @Column
    private int price;
    /** The ID of the category this product belongs to. */
    @Column
    private int categoryID;
    /**
     * Default no-argument constructor.
     */
    public Product(){}
    /**
     * Constructs a Product with the specified id, name, price, and categoryID.
     *
     * @param id the unique identifier of the product
     * @param name the name of the product
     * @param price the price of the product
     * @param categoryID the ID of the category the product belongs to
     */
    public Product(int id, String name, int price, int categoryID)
    {
        this.id=id;
        this.name=name;
        this.price=price;
        this.categoryID=categoryID;

    }
    /**
     * Returns the product's id.
     *
     * @return the id of the product
     */
    public int getID()
    {
        return(this.id);
    }
    /**
     * Returns the product's name.
     *
     * @return the name of the product
     */
    public String getName()
    {
        return(this.name);
    }
    /**
     * Returns the product's price.
     *
     * @return the price of the product
     */
    public int getPrice()
    {
        return(this.price);
    }
    /**
     * Returns the ID of the category this product belongs to.
     *
     * @return the category ID
     */
    public int getcategoryID()
    {
        return(this.categoryID);
    }
    /**
     * Sets the product's id.
     *
     * @param id the new id of the product
     */
    public void setID(int id)
    {
        this.id=id;
    }
    /**
     * Sets the product's name.
     *
     * @param name the new name of the product
     */
    public void setName(String name)
    {
        this.name=name;
    }
    /**
     * Sets the product's price.
     *
     * @param Price the new price of the product
     */
    public void setPrice(int Price)
    {
        this.price=Price;
    }
    /**
     * Sets the category ID for this product.
     *
     * @param categoryID the new category ID
     */
    public void setcategoryID(int categoryID)
    {
        this.categoryID=categoryID;
    }

}
